# Generated by Django 4.1.4 on 2022-12-12 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_alter_measurement_sensor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Измерение', 'verbose_name_plural': 'Измерения'},
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='data',
            new_name='created_at',
        ),
    ]
