# Generated by Django 4.1.4 on 2022-12-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_alter_measurement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата измерения'),
        ),
    ]
